import type { StepContent, StepId } from '../types';

/**
 * Instructional steps. Each answers WHAT (instruction), HOW (positioning points)
 * and WHAT TO SAY (recitations). Rulings are given per school where they differ;
 * `common` applies to every school unless overridden.
 *
 * Review status for every step is "draft" until approved by a qualified scholar.
 */
const steps: StepContent[] = [
  // ── Foundations ──────────────────────────────────────────────────────────────
  {
    id: 'intro',
    group: 'foundations',
    title: { en: 'Begin your Salah journey', bn: 'নামাজ শেখার যাত্রা শুরু', ar: 'ابدأ رحلة تعلّم الصلاة' },
    subtitle: { en: 'How this guide works', bn: 'নির্দেশিকাটি যেভাবে কাজ করে', ar: 'كيف يعمل هذا الدليل' },
    instruction: {
      en: 'Scroll, use Next and Previous, or tap the timeline to move through the prayer. The 3D figure moves into each position as you go.',
      bn: 'নামাজের ধাপগুলোতে এগোতে স্ক্রল করুন, “পরের” ও “আগের” বোতাম ব্যবহার করুন, অথবা টাইমলাইনে চাপুন। আপনি এগোলে ৩ডি মডেলও প্রতিটি অবস্থানে চলে যাবে।',
      ar: 'مرّر أو استخدم «التالي» و«السابق» أو انقر على الخط الزمني للتنقل بين أجزاء الصلاة، وسيتحرك المجسّم إلى كل وضعية.',
    },
    how: [
      { en: 'Switch between Front, 3/4 and Side to see the figure from different angles.', bn: 'বিভিন্ন কোণ থেকে দেখতে “সামনে”, “৩/৪” ও “পাশে” বদলান।' },
      { en: 'Soft glowing points show which parts of the body matter in each step.', bn: 'হালকা আলোকিত বিন্দুগুলো দেখায় প্রতিটি ধাপে শরীরের কোন অংশ গুরুত্বপূর্ণ।' },
      { en: 'Choose your madhhab at the top; differences between the schools are explained where they exist.', bn: 'উপরে আপনার মাযহাব বেছে নিন; যেখানে মাযহাবের পার্থক্য আছে, সেখানে তা ব্যাখ্যা করা হয়েছে।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [],
    recitations: [],
    rulings: [],
    differences: [],
    sources: ['bukhari-631'],
    review: 'draft',
  },
  {
    id: 'what-is-salah',
    group: 'foundations',
    title: { en: 'What is Salah?', bn: 'নামাজ কী?', ar: 'ما الصلاة؟' },
    subtitle: { en: 'The ritual prayer', bn: 'ফরজ ইবাদত', ar: 'العبادة المفروضة' },
    instruction: {
      en: 'Salah is the ritual prayer Muslims perform five times a day: a fixed sequence of standing, bowing, prostrating and sitting, with recitation of the Qur’an and remembrance of Allah.',
      bn: 'নামাজ হলো মুসলমানদের দৈনিক পাঁচ ওয়াক্তের ইবাদত: দাঁড়ানো, রুকু, সিজদা ও বসার একটি নির্দিষ্ট ক্রম, যার সাথে থাকে কুরআন তিলাওয়াত ও আল্লাহর জিকির।',
      ar: 'الصلاة عبادة يؤديها المسلمون خمس مرات في اليوم: قيام وركوع وسجود وجلوس على ترتيب مخصوص، مع قراءة القرآن وذكر الله.',
    },
    how: [
      { en: 'It is one of the five pillars of Islam.', bn: 'এটি ইসলামের পাঁচটি স্তম্ভের একটি।' },
      { en: 'Each prayer is made up of units called rak’ahs.', bn: 'প্রতিটি নামাজ “রাকাত” নামের কয়েকটি এককে গঠিত।' },
      { en: 'It begins with the takbir (“Allahu Akbar”) and ends with the salam.', bn: 'এটি তাকবির (“আল্লাহু আকবার”) দিয়ে শুরু হয় এবং সালাম দিয়ে শেষ হয়।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [],
    recitations: [],
    rulings: [],
    differences: [],
    sources: ['bukhari-8', 'quran-2-43', 'abudawud-61'],
    review: 'draft',
  },
  {
    id: 'why-pray',
    group: 'foundations',
    title: { en: 'Why Muslims pray', bn: 'মুসলমানরা কেন নামাজ পড়েন', ar: 'لماذا يصلي المسلمون' },
    subtitle: { en: 'Remembrance and connection', bn: 'স্মরণ ও সংযোগ', ar: 'ذكر وصلة' },
    instruction: {
      en: 'Muslims pray in obedience to Allah, as the Qur’an commands, and as a regular, direct connection with Him throughout the day.',
      bn: 'মুসলমানরা কুরআনের নির্দেশ অনুযায়ী আল্লাহর আনুগত্যে নামাজ পড়েন — এটি সারাদিন ধরে তাঁর সাথে নিয়মিত, সরাসরি সংযোগ।',
      ar: 'يصلي المسلمون طاعةً لله كما أمر القرآن، وصلةً مباشرة منتظمة به طوال اليوم.',
    },
    how: [
      { en: 'The Qur’an says: “Establish prayer for My remembrance” (20:14).', bn: 'কুরআনে বলা হয়েছে: “আমার স্মরণের জন্য নামাজ কায়েম করো” (২০:১৪)।' },
      { en: 'Prayer is described as restraining from indecency and wrongdoing (29:45).', bn: 'নামাজকে অশ্লীলতা ও অন্যায় থেকে বিরতকারী বলা হয়েছে (২৯:৪৫)।' },
      { en: 'The Prophet ﷺ compared the five prayers to bathing in a river five times a day.', bn: 'নবী ﷺ পাঁচ ওয়াক্ত নামাজকে দিনে পাঁচবার নদীতে গোসলের সাথে তুলনা করেছেন।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [],
    recitations: [],
    rulings: [],
    differences: [],
    sources: ['quran-20-14', 'quran-29-45', 'bukhari-528'],
    review: 'draft',
  },
  {
    id: 'prayer-times',
    group: 'foundations',
    title: { en: 'Prayer times', bn: 'নামাজের সময়', ar: 'أوقات الصلاة' },
    subtitle: { en: 'Five prayers, five windows of time', bn: 'পাঁচ ওয়াক্ত, পাঁচটি সময়সীমা', ar: 'خمس صلوات في خمسة أوقات' },
    instruction: {
      en: 'Each daily prayer has its own window of time: Fajr (dawn), Dhuhr (after midday), Asr (afternoon), Maghrib (after sunset) and Isha (night).',
      bn: 'প্রতিটি ওয়াক্তের নিজস্ব সময়সীমা আছে: ফজর (ভোর), যোহর (দুপুরের পর), আসর (বিকেল), মাগরিব (সূর্যাস্তের পর) ও এশা (রাত)।',
      ar: 'لكل صلاة وقتها: الفجر، والظهر بعد الزوال، والعصر، والمغرب بعد الغروب، والعشاء ليلًا.',
    },
    how: [
      { en: 'Exact times change daily with the sun — use a trusted local timetable.', bn: 'সূর্যের সাথে সময় প্রতিদিন বদলায় — নির্ভরযোগ্য স্থানীয় সময়সূচি ব্যবহার করুন।' },
      { en: 'Praying within the prescribed time is an obligation (Qur’an 4:103).', bn: 'নির্ধারিত সময়ের মধ্যে নামাজ আদায় করা ফরজ (কুরআন ৪:১০৩)।' },
      { en: 'The schools differ slightly on some boundaries, such as the start of Asr.', bn: 'কিছু সময়সীমা, যেমন আসরের শুরু, নিয়ে মাযহাবগুলোর মধ্যে সামান্য পার্থক্য আছে।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [],
    recitations: [],
    rulings: [],
    differences: [],
    sources: ['quran-4-103', 'muslim-612'],
    review: 'draft',
  },
  {
    id: 'wudu',
    group: 'foundations',
    title: { en: 'Wudu (ablution)', bn: 'অজু', ar: 'الوضوء' },
    arabicTitle: 'وُضُوء',
    subtitle: { en: 'Purify yourself before praying', bn: 'নামাজের আগে পবিত্রতা', ar: 'الطهارة قبل الصلاة' },
    instruction: {
      en: 'Before praying, perform wudu — the ritual washing described in the Qur’an.',
      bn: 'নামাজের আগে অজু করুন — কুরআনে বর্ণিত পবিত্রতা অর্জনের পদ্ধতি।',
      ar: 'توضأ قبل الصلاة كما بيّن القرآن.',
    },
    how: [
      { en: 'The Qur’an names washing the face, washing the arms to the elbows, wiping the head and washing the feet to the ankles (5:6).', bn: 'কুরআনে মুখ ধোয়া, কনুই পর্যন্ত হাত ধোয়া, মাথা মাসেহ করা এবং টাখনু পর্যন্ত পা ধোয়ার কথা বলা হয়েছে (৫:৬)।' },
      { en: 'Further practices, such as rinsing the mouth and nose, come from the Sunnah; the schools classify some of them differently.', bn: 'কুলি করা ও নাকে পানি দেওয়ার মতো অন্যান্য আমল সুন্নাহ থেকে এসেছে; এগুলোর কিছুর বিধান মাযহাবভেদে ভিন্ন।' },
      { en: 'Some things, such as using the toilet, end the state of wudu; details are covered in books of fiqh.', bn: 'টয়লেট ব্যবহারের মতো কিছু বিষয় অজু ভেঙে দেয়; বিস্তারিত ফিকহের গ্রন্থে আছে।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [{ part: 'hands', label: { en: 'Washing the hands and arms', bn: 'হাত ও বাহু ধোয়া' } }],
    recitations: [],
    rulings: [{ subject: { en: 'Being in a state of wudu', bn: 'অজু অবস্থায় থাকা' }, levels: { common: 'condition' } }],
    differences: [],
    sources: ['quran-5-6'],
    review: 'draft',
  },
  {
    id: 'qiblah',
    group: 'foundations',
    title: { en: 'Facing the Qiblah', bn: 'কিবলামুখী হওয়া', ar: 'استقبال القبلة' },
    arabicTitle: 'قِبْلَة',
    subtitle: { en: 'The direction of the Ka’bah', bn: 'কাবার দিক', ar: 'جهة الكعبة' },
    instruction: {
      en: 'Face the Qiblah — the direction of the Ka’bah in Makkah — for the whole prayer.',
      bn: 'পুরো নামাজে কিবলার দিকে — মক্কার কাবার দিকে — মুখ করে থাকুন।',
      ar: 'استقبل القبلة — جهة الكعبة في مكة — طوال الصلاة.',
    },
    how: [
      { en: 'Find the direction with a compass app or by asking at a local mosque.', bn: 'কম্পাস অ্যাপ ব্যবহার করে বা স্থানীয় মসজিদে জিজ্ঞেস করে দিক নির্ণয় করুন।' },
      { en: 'Pray on a clean surface; a prayer mat is common but not required.', bn: 'পবিত্র স্থানে নামাজ পড়ুন; জায়নামাজ প্রচলিত, তবে আবশ্যক নয়।' },
      { en: 'In the 3D scene, the Qiblah is the direction the figure faces.', bn: '৩ডি দৃশ্যে মডেলটি যেদিকে মুখ করে আছে, সেটিই কিবলা।' },
    ],
    pose: 'stand',
    camera: 'front',
    highlights: [{ part: 'feet', label: { en: 'Feet face the Qiblah', bn: 'পা কিবলামুখী' } }],
    recitations: [],
    rulings: [{ subject: { en: 'Facing the Qiblah', bn: 'কিবলামুখী হওয়া' }, levels: { common: 'condition' } }],
    differences: [],
    sources: ['quran-2-144'],
    review: 'draft',
  },
  {
    id: 'preparation',
    group: 'foundations',
    title: { en: 'Clothing & preparation', bn: 'পোশাক ও প্রস্তুতি', ar: 'اللباس والاستعداد' },
    subtitle: { en: 'Clean, covered and calm', bn: 'পবিত্র, আবৃত ও শান্ত', ar: 'طهارة وستر وسكينة' },
    instruction: {
      en: 'Wear clean clothing that covers what must be covered, and pray in a clean place.',
      bn: 'যা ঢেকে রাখা আবশ্যক তা ঢাকে এমন পবিত্র পোশাক পরুন এবং পবিত্র স্থানে নামাজ পড়ুন।',
      ar: 'البس ثيابًا طاهرة تستر العورة، وصلِّ في مكان طاهر.',
    },
    how: [
      { en: 'Body, clothes and place of prayer should be free of impurity (najasah).', bn: 'শরীর, পোশাক ও নামাজের স্থান নাপাকি (নাজাসাত) থেকে মুক্ত থাকা উচিত।' },
      { en: 'Covering the ‘awrah is a condition of the prayer; its extent differs for men and women and is detailed in fiqh.', bn: 'সতর ঢাকা নামাজের শর্ত; পুরুষ ও নারীর জন্য এর সীমা ভিন্ন এবং ফিকহে বিস্তারিত আছে।' },
      { en: 'Stand calmly with the feet a natural distance apart before you begin.', bn: 'শুরু করার আগে পা স্বাভাবিক দূরত্বে রেখে শান্তভাবে দাঁড়ান।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [{ part: 'feet', label: { en: 'Feet a natural distance apart', bn: 'পা স্বাভাবিক দূরত্বে' } }],
    recitations: [],
    rulings: [
      {
        subject: { en: 'Covering the ‘awrah', bn: 'সতর ঢাকা' },
        levels: { common: 'condition' },
        note: { en: 'Its extent and some details differ between the schools.', bn: 'এর সীমা ও কিছু খুঁটিনাটি মাযহাবভেদে ভিন্ন।' },
      },
    ],
    differences: [],
    sources: ['quran-7-31'],
    review: 'draft',
  },
  {
    id: 'niyyah',
    group: 'foundations',
    title: { en: 'Niyyah (intention)', bn: 'নিয়ত', ar: 'النية' },
    arabicTitle: 'نِيَّة',
    subtitle: { en: 'Intend the prayer in your heart', bn: 'অন্তরে নামাজের নিয়ত করুন', ar: 'انوِ الصلاة بقلبك' },
    instruction: {
      en: 'Make the intention in your heart for the specific prayer you are about to perform, such as the two rak’ahs of Fajr.',
      bn: 'যে নামাজ পড়তে যাচ্ছেন — যেমন ফজরের দুই রাকাত — অন্তরে তার নিয়ত করুন।',
      ar: 'انوِ بقلبك الصلاة المعيّنة التي ستؤديها، كركعتي الفجر.',
    },
    how: [
      { en: 'The intention is in the heart; it does not have to be spoken.', bn: 'নিয়ত অন্তরের বিষয়; মুখে বলা আবশ্যক নয়।' },
      { en: 'Know which prayer you are praying and whether it is obligatory or voluntary.', bn: 'কোন নামাজ পড়ছেন এবং তা ফরজ নাকি নফল — তা জেনে নিন।' },
      { en: 'Stand upright, facing the Qiblah, with your gaze lowered.', bn: 'দৃষ্টি নিচু রেখে কিবলামুখী হয়ে সোজা দাঁড়ান।' },
    ],
    pose: 'stand',
    camera: 'threeQuarter',
    highlights: [{ part: 'gaze', label: { en: 'Gaze lowered, heart attentive', bn: 'দৃষ্টি নিচু, মন মনোযোগী' } }],
    recitations: [],
    rulings: [
      {
        subject: { en: 'Intention', bn: 'নিয়ত' },
        levels: { hanafi: 'condition', hanbali: 'condition', shafii: 'fard', maliki: 'fard' },
        note: {
          en: 'All schools agree the prayer is invalid without it; they differ on whether it is classed as a condition or a pillar.',
          bn: 'সব মাযহাব একমত যে নিয়ত ছাড়া নামাজ হয় না; একে শর্ত নাকি রুকন বলা হবে — তাতে ভিন্নতা আছে।',
        },
      },
    ],
    differences: [],
    sources: ['bukhari-1'],
    review: 'draft',
  },

  // ── Movements ────────────────────────────────────────────────────────────────
  {
    id: 'takbir',
    group: 'movement',
    title: { en: 'Takbir al-Ihram', bn: 'তাকবিরে তাহরিমা', ar: 'تكبيرة الإحرام' },
    arabicTitle: 'تَكْبِيرَةُ الإِحْرَام',
    subtitle: { en: 'Raise the hands and enter the prayer', bn: 'হাত তুলে নামাজে প্রবেশ করুন', ar: 'ارفع يديك وادخل في الصلاة' },
    instruction: {
      en: 'Raise both hands and say “Allahu Akbar” to begin the prayer.',
      bn: 'দুই হাত তুলে “আল্লাহু আকবার” বলে নামাজ শুরু করুন।',
      ar: 'ارفع يديك وقل «الله أكبر» لتبدأ الصلاة.',
    },
    how: [
      { en: 'Raise the hands with the palms facing the Qiblah and the fingers naturally together, pointing upward.', bn: 'হাতের তালু কিবলার দিকে রেখে, আঙুল স্বাভাবিকভাবে একত্রে উপরের দিকে রেখে হাত তুলুন।' },
      { en: 'Say the takbir as the hands are raised; how high they go differs between the schools.', bn: 'হাত তোলার সময় তাকবির বলুন; হাত কতটা উঁচুতে উঠবে তা মাযহাবভেদে ভিন্ন।' },
      { en: 'From this moment, everything other than the prayer is set aside.', bn: 'এই মুহূর্ত থেকে নামাজ ছাড়া অন্য সবকিছু থেকে বিরত থাকুন।' },
    ],
    pose: 'takbir',
    camera: 'front',
    highlights: [
      { part: 'hands', label: { en: 'Palms face the Qiblah', bn: 'তালু কিবলামুখী' } },
      { part: 'head', label: { en: 'Head upright, gaze lowered', bn: 'মাথা সোজা, দৃষ্টি নিচু' } },
    ],
    recitations: ['takbir'],
    rulings: [
      {
        subject: { en: 'The opening takbir', bn: 'তাকবিরে তাহরিমা' },
        levels: { common: 'fard', hanafi: 'condition' },
        note: {
          en: 'Hanafi scholars classify it as a condition and the other schools as a pillar; all agree the prayer does not begin without it.',
          bn: 'হানাফি আলেমগণ একে শর্ত এবং অন্যান্য মাযহাব রুকন বলেন; সবাই একমত যে এটি ছাড়া নামাজ শুরু হয় না।',
        },
      },
      { subject: { en: 'Raising the hands', bn: 'হাত তোলা' }, levels: { common: 'sunnah' } },
    ],
    differences: ['takbirHands', 'raisingHands'],
    sources: ['bukhari-735', 'abudawud-61', 'bukhari-757'],
    review: 'draft',
  },
  {
    id: 'qiyam',
    group: 'movement',
    title: { en: 'Qiyam (standing)', bn: 'কিয়াম (দাঁড়ানো)', ar: 'القيام' },
    arabicTitle: 'قِيَام',
    subtitle: { en: 'Stand and place the hands', bn: 'দাঁড়িয়ে হাত বাঁধুন', ar: 'قف وضع يديك' },
    instruction: {
      en: 'Stand upright and bring the hands to rest in the position of your school, then begin with the opening supplication.',
      bn: 'সোজা হয়ে দাঁড়ান এবং আপনার মাযহাব অনুযায়ী হাত রাখুন, তারপর সানা দিয়ে শুরু করুন।',
      ar: 'قف معتدلًا وضع يديك على هيئة مذهبك، ثم ابدأ بدعاء الاستفتاح.',
    },
    how: [
      { en: 'Stand straight without stiffness, with the feet facing the Qiblah.', bn: 'শক্ত না হয়ে সোজা দাঁড়ান, পা কিবলার দিকে রাখুন।' },
      { en: 'Lower your gaze; most schools teach looking towards the place of prostration.', bn: 'দৃষ্টি নিচু রাখুন; অধিকাংশ মাযহাবে সিজদার স্থানের দিকে তাকাতে শেখানো হয়।' },
      { en: 'Hand position differs between the schools — see the notes below.', bn: 'হাত রাখার পদ্ধতি মাযহাবভেদে ভিন্ন — নিচের নোট দেখুন।' },
    ],
    pose: 'qiyam',
    camera: 'threeQuarter',
    highlights: [
      { part: 'hands', label: { en: 'Hand position', bn: 'হাতের অবস্থান' } },
      { part: 'gaze', label: { en: 'Gaze lowered', bn: 'দৃষ্টি নিচু' } },
      { part: 'feet', label: { en: 'Feet face the Qiblah', bn: 'পা কিবলামুখী' } },
    ],
    recitations: ['opening', 'taawwudh'],
    rulings: [
      { subject: { en: 'Standing in obligatory prayers (when able)', bn: 'ফরজ নামাজে দাঁড়ানো (সামর্থ্য থাকলে)' }, levels: { common: 'fard' } },
      {
        subject: { en: 'Placing the right hand over the left', bn: 'ডান হাত বাম হাতের উপর রাখা' },
        levels: { common: 'sunnah', maliki: 'notPracticed' },
        note: {
          en: 'In the well-known Maliki position the arms rest at the sides in obligatory prayers.',
          bn: 'মালেকি মাযহাবের প্রসিদ্ধ মতে ফরজ নামাজে হাত দুই পাশে ছেড়ে রাখা হয়।',
        },
      },
      { subject: { en: 'Opening supplication', bn: 'সানা' }, levels: { common: 'sunnah', maliki: 'notPracticed' } },
    ],
    differences: ['handPlacement', 'openingDua'],
    sources: ['bukhari-740', 'muslim-401', 'abudawud-775', 'quran-16-98', 'quran-2-238'],
    review: 'draft',
  },
  {
    id: 'fatiha',
    group: 'recitation',
    title: { en: 'Al-Fatihah', bn: 'সূরা ফাতিহা', ar: 'الفاتحة' },
    arabicTitle: 'الفَاتِحَة',
    subtitle: { en: 'Recite the Opening chapter', bn: 'সূরা ফাতিহা তিলাওয়াত', ar: 'قراءة فاتحة الكتاب' },
    instruction: {
      en: 'While standing, recite Surah al-Fatihah — the Opening chapter of the Qur’an — in every rak’ah.',
      bn: 'দাঁড়ানো অবস্থায় প্রতি রাকাতে সূরা ফাতিহা — কুরআনের প্রথম সূরা — তিলাওয়াত করুন।',
      ar: 'اقرأ سورة الفاتحة قائمًا في كل ركعة.',
    },
    how: [
      { en: 'Recite calmly, verse by verse, keeping the hands in place.', bn: 'হাত স্থির রেখে ধীরে ধীরে আয়াত ধরে ধরে পড়ুন।' },
      { en: 'Begin with “Bismillah”; whether it is recited aloud differs between the schools.', bn: '“বিসমিল্লাহ” দিয়ে শুরু করুন; এটি উচ্চস্বরে পড়া হবে কিনা তা মাযহাবভেদে ভিন্ন।' },
      { en: 'After the last verse, “Amin” is said.', bn: 'শেষ আয়াতের পর “আমিন” বলা হয়।' },
    ],
    pose: 'qiyam',
    camera: 'front',
    highlights: [{ part: 'gaze', label: { en: 'Stillness and focus', bn: 'স্থিরতা ও মনোযোগ' } }],
    recitations: ['fatiha'],
    rulings: [
      {
        subject: { en: 'Reciting al-Fatihah', bn: 'সূরা ফাতিহা পড়া' },
        levels: { common: 'fard', hanafi: 'wajib' },
        note: {
          en: 'Hanafi: reciting from the Qur’an is the pillar and al-Fatihah specifically is wajib. Rulings for a follower behind an imam differ between the schools.',
          bn: 'হানাফি: কুরআন থেকে তিলাওয়াত করা রুকন, আর বিশেষভাবে সূরা ফাতিহা পড়া ওয়াজিব। ইমামের পেছনে মুক্তাদির বিধান মাযহাবভেদে ভিন্ন।',
        },
      },
    ],
    differences: ['basmalah', 'ameen'],
    sources: ['bukhari-756', 'quran-1', 'bukhari-780'],
    review: 'draft',
  },
  {
    id: 'surah',
    group: 'recitation',
    title: { en: 'A further recitation', bn: 'অতিরিক্ত তিলাওয়াত', ar: 'قراءة سورة' },
    arabicTitle: 'قِرَاءَةُ السُّورَة',
    subtitle: { en: 'Recite more of the Qur’an', bn: 'কুরআনের আরও কিছু অংশ পড়ুন', ar: 'اقرأ شيئًا من القرآن' },
    instruction: {
      en: 'In the first two rak’ahs, recite some more of the Qur’an after al-Fatihah — for example Surah al-Ikhlas.',
      bn: 'প্রথম দুই রাকাতে সূরা ফাতিহার পর কুরআনের আরও কিছু অংশ পড়ুন — যেমন সূরা ইখলাস।',
      ar: 'في الركعتين الأوليين اقرأ بعد الفاتحة شيئًا من القرآن، كسورة الإخلاص.',
    },
    how: [
      { en: 'Any passage of the Qur’an may be recited; short surahs are common for beginners.', bn: 'কুরআনের যেকোনো অংশ পড়া যায়; নতুনদের জন্য ছোট সূরা প্রচলিত।' },
      { en: 'In the third and fourth rak’ahs of obligatory prayers, the common practice is al-Fatihah alone.', bn: 'ফরজ নামাজের তৃতীয় ও চতুর্থ রাকাতে সাধারণত শুধু সূরা ফাতিহা পড়া হয়।' },
      { en: 'Keep the hands in place and the body still.', bn: 'হাত স্থির রাখুন এবং শরীর নিশ্চল রাখুন।' },
    ],
    pose: 'qiyam',
    camera: 'front',
    highlights: [{ part: 'hands', label: { en: 'Hands remain in place', bn: 'হাত স্থির থাকবে' } }],
    recitations: ['ikhlas'],
    rulings: [
      {
        subject: { en: 'Additional recitation in the first two rak’ahs', bn: 'প্রথম দুই রাকাতে অতিরিক্ত তিলাওয়াত' },
        levels: { common: 'sunnah', hanafi: 'wajib' },
      },
    ],
    differences: [],
    sources: ['bukhari-776', 'quran-112'],
    review: 'draft',
  },
  {
    id: 'ruku',
    group: 'movement',
    title: { en: 'Ruku’ (bowing)', bn: 'রুকু', ar: 'الركوع' },
    arabicTitle: 'رُكُوع',
    subtitle: { en: 'Bow with a level back', bn: 'পিঠ সোজা রেখে ঝুঁকুন', ar: 'اركع مستوي الظهر' },
    instruction: {
      en: 'Say “Allahu Akbar” and bow, placing your hands on your knees with your back level.',
      bn: '“আল্লাহু আকবার” বলে রুকুতে যান; হাত হাঁটুর উপর রাখুন এবং পিঠ সমান রাখুন।',
      ar: 'قل «الله أكبر» واركع واضعًا يديك على ركبتيك مع استواء الظهر.',
    },
    how: [
      { en: 'Grip the knees with the fingers spread.', bn: 'আঙুল ফাঁক করে হাঁটু আঁকড়ে ধরুন।' },
      { en: 'Keep the back straight and level, with the head in line with it — neither raised nor lowered.', bn: 'পিঠ সোজা ও সমান রাখুন; মাথা পিঠের সমান্তরালে থাকবে — উঁচুও নয়, নিচুও নয়।' },
      { en: 'Keep the legs straight and pause until the body is still.', bn: 'পা সোজা রাখুন এবং শরীর স্থির না হওয়া পর্যন্ত থামুন।' },
    ],
    pose: 'ruku',
    camera: 'side',
    highlights: [
      { part: 'back', label: { en: 'Back level', bn: 'পিঠ সমান' } },
      { part: 'head', label: { en: 'Head in line with the back', bn: 'মাথা পিঠের সমান্তরালে' } },
      { part: 'hands', label: { en: 'Hands grip the knees', bn: 'হাত হাঁটু আঁকড়ে' } },
      { part: 'knees', label: { en: 'Legs straight', bn: 'পা সোজা' } },
    ],
    recitations: ['ruku'],
    rulings: [
      {
        subject: { en: 'Bowing, with stillness', bn: 'স্থিরতার সাথে রুকু' },
        levels: { common: 'fard' },
        note: { en: 'Hanafi scholars classify the stillness (tuma’ninah) itself as wajib.', bn: 'হানাফি আলেমগণ স্থিরতাকে (তুমানিনা) ওয়াজিব বলেন।' },
      },
      { subject: { en: 'Glorification (tasbih) in ruku’', bn: 'রুকুর তাসবিহ' }, levels: { common: 'sunnah', maliki: 'recommended', hanbali: 'wajib' } },
      { subject: { en: 'Takbir when moving between positions', bn: 'অবস্থান পরিবর্তনের তাকবির' }, levels: { common: 'sunnah', hanbali: 'wajib' } },
    ],
    differences: ['raisingHands', 'tasbihRuling'],
    sources: ['bukhari-828', 'muslim-498', 'muslim-772', 'bukhari-789', 'bukhari-757'],
    review: 'draft',
  },
  {
    id: 'itidal',
    group: 'movement',
    title: { en: 'I’tidal (rising)', bn: 'কওমা (রুকু থেকে ওঠা)', ar: 'الاعتدال' },
    arabicTitle: 'اِعْتِدَال',
    subtitle: { en: 'Stand up straight again', bn: 'আবার সোজা হয়ে দাঁড়ান', ar: 'عُد قائمًا معتدلًا' },
    instruction: {
      en: 'Rise from bowing saying “Sami’allahu liman hamidah”, stand fully upright, then say “Rabbana wa lakal-hamd”.',
      bn: '“সামিআল্লাহু লিমান হামিদাহ” বলে রুকু থেকে উঠুন, পুরোপুরি সোজা হয়ে দাঁড়ান, তারপর “রব্বানা ওয়া লাকাল হামদ” বলুন।',
      ar: 'ارفع من الركوع قائلًا «سمع الله لمن حمده»، واعتدل قائمًا، ثم قل «ربنا ولك الحمد».',
    },
    how: [
      { en: 'Return to a full, straight standing position.', bn: 'সম্পূর্ণ সোজা হয়ে দাঁড়ান।' },
      { en: 'Let the body settle completely before moving on.', bn: 'পরের ধাপে যাওয়ার আগে শরীর পুরোপুরি স্থির হতে দিন।' },
      { en: 'Let the arms rest naturally.', bn: 'হাত স্বাভাবিকভাবে রাখুন।' },
    ],
    pose: 'itidal',
    camera: 'side',
    highlights: [
      { part: 'back', label: { en: 'Fully upright', bn: 'সম্পূর্ণ সোজা' } },
      { part: 'head', label: { en: 'Head upright', bn: 'মাথা সোজা' } },
    ],
    recitations: ['rising'],
    rulings: [
      { subject: { en: 'Rising and standing upright with stillness', bn: 'রুকু থেকে উঠে স্থিরভাবে সোজা দাঁড়ানো' }, levels: { common: 'fard', hanafi: 'wajib' } },
      {
        subject: { en: '“Sami’allahu liman hamidah”', bn: '“সামিআল্লাহু লিমান হামিদাহ”' },
        levels: { common: 'sunnah', hanbali: 'wajib' },
        note: { en: 'For the imam and someone praying alone; schools differ on what a follower says.', bn: 'ইমাম ও একাকী নামাজির জন্য; মুক্তাদি কী বলবেন তাতে মাযহাবভেদ আছে।' },
      },
    ],
    differences: ['raisingHands'],
    sources: ['bukhari-789', 'bukhari-757', 'bukhari-735'],
    review: 'draft',
  },
  {
    id: 'sujood',
    group: 'movement',
    title: { en: 'Sujood (prostration)', bn: 'সিজদা', ar: 'السجود' },
    arabicTitle: 'سُجُود',
    subtitle: { en: 'Prostrate on seven parts of the body', bn: 'শরীরের সাতটি অঙ্গের উপর সিজদা', ar: 'السجود على سبعة أعظم' },
    instruction: {
      en: 'Say “Allahu Akbar” and go down into prostration, with the forehead and nose, both palms, both knees and the toes of both feet on the ground.',
      bn: '“আল্লাহু আকবার” বলে সিজদায় যান: কপাল ও নাক, দুই হাতের তালু, দুই হাঁটু এবং দুই পায়ের আঙুল মাটিতে থাকবে।',
      ar: 'قل «الله أكبر» واسجد على الجبهة والأنف واليدين والركبتين وأطراف القدمين.',
    },
    how: [
      { en: 'Place the palms flat, level with the shoulders or ears, fingers together and pointing towards the Qiblah.', bn: 'হাতের তালু কাঁধ বা কান বরাবর সমানভাবে রাখুন, আঙুল একত্রে কিবলার দিকে।' },
      { en: 'Lift the forearms off the ground and keep the arms away from the sides.', bn: 'বাহু মাটি থেকে উঠিয়ে রাখুন এবং পাঁজর থেকে দূরে রাখুন।' },
      { en: 'Bend the toes so they point towards the Qiblah, and be still. Some schools describe details differently for men and women.', bn: 'পায়ের আঙুল বাঁকিয়ে কিবলার দিকে রাখুন এবং স্থির থাকুন। কিছু মাযহাবে পুরুষ ও নারীর জন্য খুঁটিনাটি ভিন্নভাবে বর্ণিত।' },
    ],
    pose: 'sujood',
    camera: 'side',
    highlights: [
      { part: 'forehead', label: { en: 'Forehead and nose on the ground', bn: 'কপাল ও নাক মাটিতে' } },
      { part: 'hands', label: { en: 'Palms flat', bn: 'তালু সমানভাবে' } },
      { part: 'knees', label: { en: 'Knees on the ground', bn: 'হাঁটু মাটিতে' } },
      { part: 'toes', label: { en: 'Toes bent towards the Qiblah', bn: 'পায়ের আঙুল কিবলামুখী' } },
    ],
    recitations: ['sujood'],
    rulings: [
      {
        subject: { en: 'Prostration, with stillness', bn: 'স্থিরতার সাথে সিজদা' },
        levels: { common: 'fard' },
        note: {
          en: 'The schools differ on which of the seven parts are strictly required, and Hanafi scholars classify stillness as wajib.',
          bn: 'সাত অঙ্গের কোনগুলো অবশ্যই মাটিতে থাকতে হবে তা নিয়ে মাযহাবভেদ আছে; হানাফি আলেমগণ স্থিরতাকে ওয়াজিব বলেন।',
        },
      },
      { subject: { en: 'Glorification (tasbih) in sujood', bn: 'সিজদার তাসবিহ' }, levels: { common: 'sunnah', maliki: 'recommended', hanbali: 'wajib' } },
    ],
    differences: ['descent', 'tasbihRuling'],
    sources: ['bukhari-812', 'muslim-772', 'bukhari-828', 'muslim-498'],
    review: 'draft',
  },
  {
    id: 'jalsa',
    group: 'movement',
    title: { en: 'Jalsa (sitting)', bn: 'জলসা (দুই সিজদার মাঝে বসা)', ar: 'الجلسة بين السجدتين' },
    arabicTitle: 'جَلْسَة',
    subtitle: { en: 'Sit briefly between the two prostrations', bn: 'দুই সিজদার মাঝে অল্প সময় বসুন', ar: 'اجلس قليلًا بين السجدتين' },
    instruction: {
      en: 'Rise from prostration saying “Allahu Akbar” and sit upright, then pause.',
      bn: '“আল্লাহু আকবার” বলে সিজদা থেকে উঠে সোজা হয়ে বসুন এবং কিছুক্ষণ থামুন।',
      ar: 'ارفع من السجود قائلًا «الله أكبر» واجلس معتدلًا مطمئنًا.',
    },
    how: [
      { en: 'Sit in the posture of your school (see notes); commonly on the left foot laid flat, with the right foot upright.', bn: 'আপনার মাযহাবের পদ্ধতিতে বসুন (নোট দেখুন); সাধারণত বাম পা বিছিয়ে তার উপর, ডান পা খাড়া রেখে।' },
      { en: 'Rest the hands on the thighs, near the knees.', bn: 'হাত হাঁটুর কাছাকাছি উরুর উপর রাখুন।' },
      { en: 'Sit still until each part of the body settles.', bn: 'শরীরের প্রতিটি অংশ স্থির না হওয়া পর্যন্ত বসে থাকুন।' },
    ],
    pose: 'jalsa',
    camera: 'threeQuarter',
    highlights: [
      { part: 'seat', label: { en: 'Sitting posture', bn: 'বসার পদ্ধতি' } },
      { part: 'toes', label: { en: 'Right foot upright', bn: 'ডান পা খাড়া' } },
      { part: 'hands', label: { en: 'Hands on the thighs', bn: 'হাত উরুর উপর' } },
    ],
    recitations: ['betweenSujood'],
    rulings: [
      { subject: { en: 'Sitting between the prostrations, with stillness', bn: 'দুই সিজদার মাঝে স্থিরভাবে বসা' }, levels: { common: 'fard', hanafi: 'wajib' } },
      { subject: { en: 'Supplication between the prostrations', bn: 'দুই সিজদার মাঝের দোয়া' }, levels: { common: 'sunnah', maliki: 'recommended', hanbali: 'wajib' } },
    ],
    differences: ['sittingPosture'],
    sources: ['muslim-498', 'abudawud-874', 'bukhari-757'],
    review: 'draft',
  },
  {
    id: 'sujood-second',
    group: 'movement',
    title: { en: 'Second sujood', bn: 'দ্বিতীয় সিজদা', ar: 'السجدة الثانية' },
    arabicTitle: 'السَّجْدَةُ الثَّانِيَة',
    subtitle: { en: 'Prostrate again', bn: 'আবার সিজদা করুন', ar: 'اسجد مرة أخرى' },
    instruction: {
      en: 'Say “Allahu Akbar” and make a second prostration exactly like the first.',
      bn: '“আল্লাহু আকবার” বলে প্রথমটির মতোই দ্বিতীয় সিজদা করুন।',
      ar: 'قل «الله أكبر» واسجد سجدة ثانية كالأولى.',
    },
    how: [
      { en: 'The same seven parts touch the ground.', bn: 'একই সাতটি অঙ্গ মাটিতে থাকবে।' },
      { en: 'Repeat the glorification calmly.', bn: 'ধীরে ধীরে তাসবিহ পড়ুন।' },
      { en: 'This completes the rak’ah.', bn: 'এর মাধ্যমে একটি রাকাত সম্পূর্ণ হয়।' },
    ],
    pose: 'sujood',
    camera: 'side',
    highlights: [
      { part: 'forehead', label: { en: 'Forehead and nose on the ground', bn: 'কপাল ও নাক মাটিতে' } },
      { part: 'hands', label: { en: 'Palms flat', bn: 'তালু সমানভাবে' } },
    ],
    recitations: ['sujood'],
    rulings: [{ subject: { en: 'The second prostration', bn: 'দ্বিতীয় সিজদা' }, levels: { common: 'fard' } }],
    differences: [],
    sources: ['bukhari-757', 'bukhari-812'],
    review: 'draft',
  },
  {
    id: 'rise',
    group: 'movement',
    title: { en: 'Rising for the next rak’ah', bn: 'পরের রাকাতের জন্য দাঁড়ানো', ar: 'القيام للركعة التالية' },
    subtitle: { en: 'Stand and repeat the pattern', bn: 'দাঁড়িয়ে একই ক্রম পুনরাবৃত্তি করুন', ar: 'قم وكرّر الترتيب' },
    instruction: {
      en: 'Say “Allahu Akbar” and stand up for the next rak’ah, which follows the same pattern without the opening takbir.',
      bn: '“আল্লাহু আকবার” বলে পরের রাকাতের জন্য দাঁড়ান; এটি তাকবিরে তাহরিমা ছাড়া একই ক্রমে চলে।',
      ar: 'قل «الله أكبر» وقم للركعة التالية، وهي على الترتيب نفسه دون تكبيرة الإحرام.',
    },
    how: [
      { en: 'Rise to standing and place the hands as before.', bn: 'দাঁড়িয়ে আগের মতো হাত রাখুন।' },
      { en: 'Begin again with al-Fatihah.', bn: 'আবার সূরা ফাতিহা দিয়ে শুরু করুন।' },
      { en: 'Some schools include a brief sitting before rising — see the notes.', bn: 'কিছু মাযহাবে দাঁড়ানোর আগে সামান্য বসার কথা আছে — নোট দেখুন।' },
    ],
    pose: 'qiyam',
    camera: 'threeQuarter',
    highlights: [{ part: 'hands', label: { en: 'Hands placed again', bn: 'আবার হাত রাখা' } }],
    recitations: ['takbir'],
    rulings: [],
    differences: ['restSitting'],
    sources: ['bukhari-823', 'bukhari-739'],
    review: 'draft',
  },
  {
    id: 'tashahhud',
    group: 'movement',
    title: { en: 'Tashahhud', bn: 'তাশাহহুদ', ar: 'التشهد' },
    arabicTitle: 'التَّشَهُّد',
    subtitle: { en: 'Sit and bear witness', bn: 'বসে সাক্ষ্য দিন', ar: 'اجلس واشهد' },
    instruction: {
      en: 'After the second prostration of the second rak’ah — and in the final sitting — sit and recite the tashahhud.',
      bn: 'দ্বিতীয় রাকাতের দ্বিতীয় সিজদার পর — এবং শেষ বৈঠকে — বসে তাশাহহুদ পড়ুন।',
      ar: 'بعد السجدة الثانية من الركعة الثانية — وفي الجلوس الأخير — اجلس واقرأ التشهد.',
    },
    how: [
      { en: 'Sit in the posture of your school, with the hands resting on the thighs.', bn: 'আপনার মাযহাবের পদ্ধতিতে বসুন, হাত উরুর উপর রাখুন।' },
      { en: 'The right index finger is raised during the testimony; when and how it moves differs between the schools.', bn: 'সাক্ষ্য দেওয়ার সময় ডান হাতের শাহাদাত আঙুল তোলা হয়; কখন ও কীভাবে — তা মাযহাবভেদে ভিন্ন।' },
      { en: 'In three- and four-rak’ah prayers, rise after the first tashahhud; in the final sitting, continue with the salawat.', bn: 'তিন ও চার রাকাতের নামাজে প্রথম তাশাহহুদের পর দাঁড়িয়ে যান; শেষ বৈঠকে দরুদ পড়ুন।' },
    ],
    pose: 'finalSitting',
    camera: 'threeQuarter',
    highlights: [
      { part: 'index', label: { en: 'Right index finger', bn: 'ডান হাতের শাহাদাত আঙুল' } },
      { part: 'hands', label: { en: 'Hands on the thighs', bn: 'হাত উরুর উপর' } },
      { part: 'seat', label: { en: 'Sitting posture', bn: 'বসার পদ্ধতি' } },
    ],
    recitations: ['tashahhud'],
    rulings: [
      {
        subject: { en: 'The final sitting', bn: 'শেষ বৈঠক' },
        levels: { common: 'fard' },
        note: { en: 'The schools differ on its required length.', bn: 'এর আবশ্যক দৈর্ঘ্য নিয়ে মাযহাবভেদ আছে।' },
      },
      { subject: { en: 'Reciting the final tashahhud', bn: 'শেষ বৈঠকে তাশাহহুদ পড়া' }, levels: { common: 'fard', hanafi: 'wajib', maliki: 'sunnah' } },
      {
        subject: { en: 'The first sitting and its tashahhud (3–4 rak’ah prayers)', bn: 'প্রথম বৈঠক ও তার তাশাহহুদ (৩–৪ রাকাতের নামাজ)' },
        levels: { common: 'sunnah', hanafi: 'wajib', hanbali: 'wajib' },
      },
    ],
    differences: ['sittingPosture', 'fingerPointing', 'tashahhudWording'],
    sources: ['bukhari-831', 'muslim-580', 'bukhari-828'],
    review: 'draft',
  },
  {
    id: 'salawat',
    group: 'recitation',
    title: { en: 'Salawat Ibrahimiyyah', bn: 'দরুদে ইবরাহিম', ar: 'الصلاة الإبراهيمية' },
    arabicTitle: 'الصَّلَاةُ الإِبْرَاهِيمِيَّة',
    subtitle: { en: 'Send blessings upon the Prophet ﷺ', bn: 'নবী ﷺ-এর উপর দরুদ', ar: 'الصلاة على النبي ﷺ' },
    instruction: {
      en: 'In the final sitting, after the tashahhud, send blessings upon the Prophet ﷺ.',
      bn: 'শেষ বৈঠকে তাশাহহুদের পর নবী ﷺ-এর উপর দরুদ পড়ুন।',
      ar: 'في الجلوس الأخير بعد التشهد صلِّ على النبي ﷺ.',
    },
    how: [
      { en: 'Remain seated in the same posture.', bn: 'একই ভঙ্গিতে বসে থাকুন।' },
      { en: 'Several authentic wordings exist; the one shown is reported in Sahih al-Bukhari.', bn: 'কয়েকটি বিশুদ্ধ শব্দাবলি আছে; এখানে দেখানোটি সহিহ বুখারিতে বর্ণিত।' },
    ],
    pose: 'finalSitting',
    camera: 'threeQuarter',
    highlights: [{ part: 'seat', label: { en: 'Remain seated', bn: 'বসে থাকুন' } }],
    recitations: ['salawat'],
    rulings: [{ subject: { en: 'Salawat in the final sitting', bn: 'শেষ বৈঠকে দরুদ' }, levels: { common: 'sunnah', shafii: 'fard', hanbali: 'fard' } }],
    differences: [],
    sources: ['bukhari-3370'],
    review: 'draft',
  },
  {
    id: 'dua',
    group: 'recitation',
    title: { en: 'Supplication', bn: 'দোয়া', ar: 'الدعاء' },
    subtitle: { en: 'Ask Allah before ending the prayer', bn: 'নামাজ শেষ করার আগে আল্লাহর কাছে চান', ar: 'ادعُ الله قبل الختام' },
    instruction: {
      en: 'Before the salam you may supplicate. One commonly taught supplication from the Qur’an is shown here.',
      bn: 'সালামের আগে দোয়া করতে পারেন। কুরআন থেকে বহুল প্রচলিত একটি দোয়া এখানে দেখানো হলো।',
      ar: 'يُدعى قبل السلام، وهذا دعاء قرآني شائع التعليم.',
    },
    how: [
      { en: 'Many authentic supplications are reported; this is one example.', bn: 'অনেক বিশুদ্ধ দোয়া বর্ণিত আছে; এটি একটি উদাহরণ।' },
      { en: 'Stay seated and still.', bn: 'স্থিরভাবে বসে থাকুন।' },
    ],
    pose: 'finalSitting',
    camera: 'threeQuarter',
    highlights: [],
    recitations: ['dua'],
    rulings: [{ subject: { en: 'Supplication before the salam', bn: 'সালামের আগে দোয়া' }, levels: { common: 'sunnah', maliki: 'recommended' } }],
    differences: [],
    sources: ['quran-2-201'],
    review: 'draft',
  },
  {
    id: 'salam-right',
    group: 'closing',
    title: { en: 'Salam to the right', bn: 'ডানে সালাম', ar: 'التسليم يمينًا' },
    arabicTitle: 'التَّسْلِيم',
    subtitle: { en: 'Turn the head to the right', bn: 'মাথা ডানে ফেরান', ar: 'التفت بوجهك يمينًا' },
    instruction: {
      en: 'Turn your face to the right and say “As-salamu ’alaykum wa rahmatullah”.',
      bn: 'মুখ ডান দিকে ফিরিয়ে বলুন “আস-সালামু আলাইকুম ওয়া রাহমাতুল্লাহ”।',
      ar: 'التفت بوجهك يمينًا وقل «السلام عليكم ورحمة الله».',
    },
    how: [
      { en: 'Turn the head only; the body stays seated and facing the Qiblah.', bn: 'শুধু মাথা ফেরান; শরীর কিবলামুখী হয়ে বসে থাকবে।' },
      { en: 'Turn far enough that the cheek could be seen from behind.', bn: 'এতটা ফেরান যেন পেছন থেকে গাল দেখা যায়।' },
    ],
    pose: 'salamRight',
    camera: 'front',
    highlights: [{ part: 'head', label: { en: 'Turn the head', bn: 'মাথা ফেরান' } }],
    recitations: ['salam'],
    rulings: [{ subject: { en: 'Ending the prayer with the salam', bn: 'সালামের মাধ্যমে নামাজ শেষ করা' }, levels: { common: 'fard', hanafi: 'wajib' } }],
    differences: ['salam'],
    sources: ['muslim-582', 'abudawud-996', 'abudawud-61'],
    review: 'draft',
  },
  {
    id: 'salam-left',
    group: 'closing',
    title: { en: 'Salam to the left', bn: 'বামে সালাম', ar: 'التسليم يسارًا' },
    arabicTitle: 'التَّسْلِيم',
    subtitle: { en: 'Turn the head to the left', bn: 'মাথা বামে ফেরান', ar: 'التفت بوجهك يسارًا' },
    instruction: {
      en: 'Turn your face to the left and say “As-salamu ’alaykum wa rahmatullah” again.',
      bn: 'মুখ বাম দিকে ফিরিয়ে আবার বলুন “আস-সালামু আলাইকুম ওয়া রাহমাতুল্লাহ”।',
      ar: 'التفت بوجهك يسارًا وقل «السلام عليكم ورحمة الله» مرة أخرى.',
    },
    how: [
      { en: 'Again, turn only the head.', bn: 'আবারও শুধু মাথা ফেরান।' },
      { en: 'The prayer is now complete.', bn: 'এখন নামাজ সম্পন্ন।' },
    ],
    pose: 'salamLeft',
    camera: 'front',
    highlights: [{ part: 'head', label: { en: 'Turn the head', bn: 'মাথা ফেরান' } }],
    recitations: ['salam'],
    rulings: [{ subject: { en: 'The second salam', bn: 'দ্বিতীয় সালাম' }, levels: { common: 'sunnah', hanafi: 'wajib', hanbali: 'fard', maliki: 'notPracticed' } }],
    differences: ['salam'],
    sources: ['muslim-582', 'abudawud-996'],
    review: 'draft',
  },
  {
    id: 'complete',
    group: 'closing',
    title: { en: 'Prayer complete', bn: 'নামাজ সম্পন্ন', ar: 'اكتملت الصلاة' },
    subtitle: { en: 'Remembrance after the prayer', bn: 'নামাজের পর জিকির', ar: 'الذكر بعد الصلاة' },
    instruction: {
      en: 'The prayer is complete. Remaining seated for remembrance of Allah afterwards is widely encouraged.',
      bn: 'নামাজ সম্পন্ন হয়েছে। এরপর বসে আল্লাহর জিকির করা ব্যাপকভাবে উৎসাহিত।',
      ar: 'اكتملت الصلاة، ويُستحب الجلوس بعدها لذكر الله.',
    },
    how: [
      { en: 'Review any step from the timeline below.', bn: 'নিচের টাইমলাইন থেকে যেকোনো ধাপ আবার দেখুন।' },
      { en: 'Try Practice mode to test the sequence.', bn: 'ক্রমটি যাচাই করতে অনুশীলন মোড ব্যবহার করুন।' },
      { en: 'Use Quick Reference for the structure of each daily prayer.', bn: 'প্রতিটি ওয়াক্তের কাঠামো জানতে সংক্ষিপ্ত নির্দেশিকা দেখুন।' },
    ],
    pose: 'jalsa',
    camera: 'threeQuarter',
    highlights: [],
    recitations: [],
    rulings: [],
    differences: [],
    sources: [],
    review: 'draft',
  },
];

export const STEPS: Record<StepId, StepContent> = Object.fromEntries(steps.map((s) => [s.id, s])) as Record<StepId, StepContent>;

/** Steps counted for each progress category. */
export const PROGRESS_GROUPS = {
  basics: ['what-is-salah', 'why-pray', 'prayer-times', 'wudu', 'qiblah', 'preparation', 'niyyah'] as StepId[],
  movements: ['takbir', 'qiyam', 'ruku', 'itidal', 'sujood', 'jalsa', 'tashahhud', 'salam-right'] as StepId[],
};
